services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_DATABASE=enigmask
      - MONGO_INITDB_ROOT_USERNAME=andyyo
      - MONGO_INITDB_ROOT_PASSWORD=andyyo
  mongo-express:
      image: mongo-express
      container_name: mongo_express
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - mongodb
      environment:
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=andyyo
        - ME_CONFIG_MONGODB_ADMINPASSWORD=andyyo
        - ME_CONFIG_BASICAUTH_USERNAME=andyyo
        - ME_CONFIG_BASICAUTH_PASSWORD=andyyo
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_DATABASE=enigmask
        - ME_CONFIG_MONGODB_PORT=27017
volumes:
  mongo: {}
